[package]
name = "zkdiffpriv"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
orion = { git = "https://github.com/gizatechxyz/onnx-cairo" }
# alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git" }